language: java
jdk:
    - openjdk8

matrix:
    include:
        -   os: linux
            jdk: openjdk8
    allow_failures:
        -   jdk: openjdk-ea

addons:
    sonarcloud:
        organization: "bard-framework"
        token:
            secure: ${SOANR_TOKEN}

script:
    - mvn clean package

after_success:
    - mvn clean jacoco:report install coveralls:report sonar:sonar -Dsonar.projectKey=bard-framework_jalali-date
