language: java
os:
  - linux
dist: xenial
jdk:
  - openjdk14

addons:
  sonarcloud:
    organization: "bardframework"
    token: $SOANR_TOKEN

script:
  - mvn clean package

after_success:
  - mvn clean jacoco:report install coveralls:report sonar:sonar -Dsonar.projectKey=bardframework_jalali-date
