language: java
jdk:
    - openjdk8
    - openjdk11
    - openjdk13

matrix:
    include:
        -   os: linux
            jdk: openjdk8
    allow_failures:
        -   jdk: openjdk-ea

script:
    - mvn

after_success:
    - mvn clean package
